# Generated by Django 3.1.8 on 2021-04-12 15:27

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_professors_subjects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'ordering': ['subject_code'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AddField(
            model_name='subjects',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='lab_or_lec',
            field=models.CharField(choices=[('Laboratory', 'Laboratory'), ('Lecture', 'Lecture')], default='Laboratory', max_length=200),
        ),
        migrations.AddField(
            model_name='subjects',
            name='prerequisites',
            field=modelcluster.fields.ParentalManyToManyField(to='home.Subjects'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(help_text='Ex. CS33', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='units',
            field=models.IntegerField(default=1),
        ),
    ]
