# Generated by Django 3.1.8 on 2021-04-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210412_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='sem',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default='First', max_length=200),
        ),
    ]
