# Generated by Django 3.1.8 on 2021-04-19 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210419_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sections',
            options={'ordering': ['section_name'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.RenameField(
            model_name='sections',
            old_name='deparment',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='coursecurriculum',
            name='ending_year',
            field=models.PositiveIntegerField(help_text='Use the following format: <YYYY> ex: 2012', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='coursecurriculum',
            name='starting_year',
            field=models.PositiveIntegerField(help_text='Use the following format: <YYYY> ex: 2012', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
