# Generated by Django 3.1.8 on 2021-04-12 20:42

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210412_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='Ex. CS33', max_length=300, null=True)),
                ('course_date', models.DateField()),
                ('prerequisites', modelcluster.fields.ParentalManyToManyField(blank=True, to='home.Subjects')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['course_name'],
            },
        ),
        migrations.DeleteModel(
            name='Professors',
        ),
    ]
