# Generated by Django 3.1.8 on 2021-04-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210412_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecurriculum',
            options={'ordering': ['course_name'], 'verbose_name': 'Course Curriculum', 'verbose_name_plural': 'Course Curriculum'},
        ),
        migrations.RenameField(
            model_name='coursecurriculum',
            old_name='prerequisites',
            new_name='subjects',
        ),
    ]
