# Generated by Django 3.1.8 on 2021-04-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210414_0036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectsOrderable',
        ),
    ]
