# Generated by Django 3.1.8 on 2021-04-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_subjectsorderable_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professors',
            options={'ordering': ['last_name'], 'verbose_name': 'Professor', 'verbose_name_plural': 'Professors'},
        ),
        migrations.AddField(
            model_name='professors',
            name='first_name',
            field=models.CharField(help_text='Ex. John', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='professors',
            name='last_name',
            field=models.CharField(help_text='Ex. Doe', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='professors',
            name='middle_name',
            field=models.CharField(help_text='Ex. Michael', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='professors',
            name='preferred_end_time',
            field=models.TimeField(blank=True, help_text='At most 7:00 P.M.', null=True),
        ),
        migrations.AddField(
            model_name='professors',
            name='preferred_start_time',
            field=models.TimeField(blank=True, help_text='At least 7:00 A.M.', null=True),
        ),
        migrations.AddField(
            model_name='professors',
            name='status',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Part-time', 'Part-time')], default='Regular', max_length=200),
        ),
    ]
