# Generated by Django 3.1.8 on 2021-04-16 03:44

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210415_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='preferred_end_time',
            field=models.TimeField(blank=True, help_text='At most 19:00', null=True, validators=[home.models.Professors.validate_end_time]),
        ),
        migrations.AlterField(
            model_name='professors',
            name='preferred_start_time',
            field=models.TimeField(blank=True, help_text='At least 7:00', null=True, validators=[home.models.Professors.validate_start_time]),
        ),
        migrations.DeleteModel(
            name='SubjectsOrderable',
        ),
    ]
