# Generated by Django 3.1.8 on 2021-04-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_department_room'),
        ('home', '0022_professorsschedule_roomsschedule_sectionsschedule'),
    ]

    operations = [
    ]
