# Generated by Django 3.1.8 on 2021-04-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_professorsschedule_roomsschedule_sectionsschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colleges',
            options={'ordering': ['college_name'], 'verbose_name': 'College', 'verbose_name_plural': 'Colleges'},
        ),
        migrations.AddField(
            model_name='colleges',
            name='college_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
