# Generated by Django 3.1.8 on 2021-05-18 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20210518_1317'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name requried', max_length=255, null=True)),
                ('middle_name', models.CharField(help_text='Middle name requried', max_length=255, null=True)),
                ('last_name', models.CharField(help_text='Last name requried', max_length=255, null=True)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.sections')),
            ],
            options={
                'verbose_name': 'Scheduler',
                'verbose_name_plural': 'Schedulers',
            },
        ),
        migrations.DeleteModel(
            name='AdminsAccount',
        ),
        migrations.AlterModelOptions(
            name='professorsaccount',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professors'},
        ),
        migrations.AlterModelOptions(
            name='studentsaccount',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='professorsaccount',
            name='first_name',
            field=models.CharField(help_text='First name requried', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professorsaccount',
            name='last_name',
            field=models.CharField(help_text='Last name requried', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professorsaccount',
            name='middle_name',
            field=models.CharField(help_text='Middle name requried', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professorsaccount',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.sections'),
        ),
        migrations.AddField(
            model_name='studentsaccount',
            name='first_name',
            field=models.CharField(help_text='First name requried', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsaccount',
            name='last_name',
            field=models.CharField(help_text='Last name requried', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsaccount',
            name='middle_name',
            field=models.CharField(help_text='Middle name requried', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsaccount',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.sections'),
        ),
    ]
