# Generated by Django 3.1.8 on 2021-05-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210518_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorsaccount',
            name='scheduler',
            field=models.CharField(choices=[('scheduler', 'Scheduler')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='SchedulerAccount',
        ),
    ]
