# Generated by Django 3.1.8 on 2021-05-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210527_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='professors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='professors',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='professors',
            name='middle_name',
            field=models.CharField(help_text='Ex. Michael', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='middle_name',
            field=models.CharField(help_text='Ex. Michael', max_length=1, null=True),
        ),
    ]
