# Generated by Django 3.1.8 on 2021-06-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('room_schedule', '0002_scheduledroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledRoom',
        ),
    ]
