# Generated by Django 3.1.8 on 2021-06-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210617_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='professors',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
