# Generated by Django 3.1.8 on 2021-06-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_professors_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='middle_name',
            field=models.CharField(help_text='Ex. Michael', max_length=1, null=True, verbose_name='middle initial'),
        ),
        migrations.AlterField(
            model_name='students',
            name='middle_name',
            field=models.CharField(help_text='Ex. Michael', max_length=1, null=True, verbose_name='middle initial'),
        ),
    ]
