# Generated by Django 3.1.8 on 2021-06-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210617_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='professors',
            name='is_scheduler',
            field=models.BooleanField(default=False),
        ),
    ]
