# Generated by Django 3.1.8 on 2021-06-21 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_students_choose_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professors',
            name='units',
        ),
    ]
