# Generated by Django 3.1.8 on 2021-06-03 08:55

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectsorderable',
            old_name='course_curriculum_model1',
            new_name='first_year_first_sem',
        ),
        migrations.RenameField(
            model_name='subjectsorderable',
            old_name='course_curriculum_model2',
            new_name='first_year_second_sem',
        ),
        migrations.RenameField(
            model_name='subjectsorderable',
            old_name='course_curriculum_model7',
            new_name='fourth_year_first_sem',
        ),
        migrations.RenameField(
            model_name='subjectsorderable',
            old_name='course_curriculum_model8',
            new_name='fourth_year_second_sem',
        ),
        migrations.RenameField(
            model_name='subjectsorderable',
            old_name='course_curriculum_model3',
            new_name='second_year_first_sem',
        ),
        migrations.RenameField(
            model_name='subjectsorderable',
            old_name='course_curriculum_model4',
            new_name='second_year_second_sem',
        ),
        migrations.RenameField(
            model_name='subjectsorderable',
            old_name='course_curriculum_model5',
            new_name='third_year_first_sem',
        ),
        migrations.RenameField(
            model_name='subjectsorderable',
            old_name='course_curriculum_model6',
            new_name='third_year_second_sem',
        ),
        migrations.RemoveField(
            model_name='subjectsorderable',
            name='subject_model',
        ),
        migrations.AddField(
            model_name='coursecurriculum',
            name='course_abbreviation',
            field=models.CharField(help_text='Ex. BSCS', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='choose_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administrator.departments', verbose_name='department'),
        ),
        migrations.AddField(
            model_name='subjectsorderable',
            name='co_requisite',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_requisite', to='administrator.subjects'),
        ),
        migrations.AddField(
            model_name='subjectsorderable',
            name='pre_requisite',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_requisite', to='administrator.subjects'),
        ),
        migrations.AlterField(
            model_name='coursecurriculum',
            name='course_name',
            field=models.CharField(help_text='Ex. Bachelor of Science in Computer Science', max_length=300, null=True),
        ),
    ]
