# Generated by Django 3.1.8 on 2021-06-03 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20210603_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecurriculum',
            name='department',
        ),
        migrations.AddField(
            model_name='coursecurriculum',
            name='choose_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administrator.departments', verbose_name='department'),
        ),
    ]
