# Generated by Django 3.1.8 on 2021-06-03 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20210603_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulksections',
            name='ns_first_year',
        ),
        migrations.RemoveField(
            model_name='bulksections',
            name='ns_fourth_year',
        ),
        migrations.RemoveField(
            model_name='bulksections',
            name='ns_second_year',
        ),
        migrations.RemoveField(
            model_name='bulksections',
            name='ns_third_year',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='department',
        ),
        migrations.AddField(
            model_name='rooms',
            name='choose_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='administrator.departments', verbose_name='department'),
        ),
    ]
