# Generated by Django 3.1.8 on 2021-06-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20210603_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectsorderable',
            name='co_requisite',
        ),
        migrations.RemoveField(
            model_name='subjectsorderable',
            name='pre_requisite',
        ),
    ]
