# Generated by Django 3.1.8 on 2021-05-28 09:32

from django.db import migrations, models
import django.db.models.deletion
import home.models
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorsSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RoomsSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SectionsSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Professors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Ex. John', max_length=300, null=True)),
                ('middle_name', models.CharField(help_text='Ex. Michael', max_length=300, null=True)),
                ('last_name', models.CharField(help_text='Ex. Doe', max_length=300, null=True)),
                ('preferred_start_time', models.TimeField(blank=True, default=' 7:00 AM', help_text='At least 7:00 A.M.', null=True, validators=[home.models.Professors.validate_start_time])),
                ('preferred_end_time', models.TimeField(blank=True, default=' 7:00 PM', help_text='At most 7:00 P.M.', null=True, validators=[home.models.Professors.validate_end_time])),
                ('status', models.CharField(choices=[('Regular', 'Regular'), ('Part-time', 'Part-time')], default='Regular', max_length=200)),
                ('choose_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.departments')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
                'ordering': ['last_name'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='BulkSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default='First', max_length=200)),
                ('first_year', models.IntegerField(default=0, null=True)),
                ('second_year', models.IntegerField(default=0, null=True)),
                ('third_year', models.IntegerField(default=0, null=True)),
                ('fourth_year', models.IntegerField(default=0, null=True)),
                ('ns_first_year', models.IntegerField(default=0, null=True, verbose_name='First Year')),
                ('ns_second_year', models.IntegerField(default=0, null=True, verbose_name='Second Year')),
                ('ns_third_year', models.IntegerField(default=0, null=True, verbose_name='Third Year')),
                ('ns_fourth_year', models.IntegerField(default=0, null=True, verbose_name='Fourth Year')),
                ('course_curriculum', models.ForeignKey(help_text='Ex. Computer Science', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.coursecurriculum')),
            ],
            options={
                'verbose_name': 'Bulk Section',
                'verbose_name_plural': 'Bulk Section',
                'ordering': ['course_curriculum__course_name'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
    ]
