# Generated by Django 3.1.8 on 2021-04-19 16:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_coursecurriculum_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecurriculum',
            name='department',
            field=models.ForeignKey(help_text='Ex. Computer Studies', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.departments'),
        ),
        migrations.AlterField(
            model_name='coursecurriculum',
            name='college',
            field=models.ForeignKey(help_text='Ex. COS or College of Science', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.colleges'),
        ),
        migrations.AlterField(
            model_name='coursecurriculum',
            name='ending_year',
            field=models.PositiveIntegerField(help_text='Use the following format: <YYYY> ex: 2012', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2020)]),
        ),
        migrations.AlterField(
            model_name='coursecurriculum',
            name='starting_year',
            field=models.PositiveIntegerField(help_text='Use the following format: <YYYY> ex: 2012', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2020)]),
        ),
    ]
