# Generated by Django 3.1.8 on 2021-05-29 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bulksections_professors_professorsschedule_roomsschedule_sectionsschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='department',
        ),
        migrations.AlterField(
            model_name='departments',
            name='Choose_College',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colleges', verbose_name='College'),
        ),
    ]
