# Generated by Django 3.1.8 on 2021-04-19 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210419_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='college',
            field=models.ForeignKey(help_text='Ex. COS or College of Science', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.colleges'),
        ),
        migrations.AddField(
            model_name='sections',
            name='course_curriculum',
            field=models.ForeignKey(help_text='Ex. COS or College of Science', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.coursecurriculum'),
        ),
        migrations.AddField(
            model_name='sections',
            name='deparment',
            field=models.ForeignKey(help_text='Ex. COS or College of Science', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.departments'),
        ),
        migrations.AddField(
            model_name='sections',
            name='section_name',
            field=models.CharField(help_text='Ex. BSCS-3A-NS', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sections',
            name='sem',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default='First', max_length=200),
        ),
        migrations.AddField(
            model_name='sections',
            name='year_level',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default='First', max_length=200),
        ),
    ]
