# Generated by Django 3.1.8 on 2021-06-02 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210529_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='choose_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.departments'),
        ),
    ]
