# Generated by Django 3.1.8 on 2021-06-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210602_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulksections',
            name='ns_first_year',
        ),
        migrations.RemoveField(
            model_name='bulksections',
            name='ns_fourth_year',
        ),
        migrations.RemoveField(
            model_name='bulksections',
            name='ns_second_year',
        ),
        migrations.RemoveField(
            model_name='bulksections',
            name='ns_third_year',
        ),
    ]
