# Generated by Django 3.1.8 on 2021-06-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210602_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecurriculum',
            name='course_abbreviation',
            field=models.CharField(help_text='Ex. BSCS', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sections',
            name='section_name',
            field=models.CharField(help_text='Ex. BSCS-NS-3A', max_length=30, null=True),
        ),
    ]
