# Generated by Django 3.1.8 on 2021-05-04 12:31

from django.db import migrations, models
import django.db.models.deletion
import home.models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_loginpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='preferred_end_time',
            field=models.TimeField(blank=True, default=' 7:00 PM', help_text='At most 7:00 P.M.', null=True, validators=[home.models.Professors.validate_end_time]),
        ),
        migrations.AlterField(
            model_name='professors',
            name='preferred_start_time',
            field=models.TimeField(blank=True, default=' 7:00 AM', help_text='At least 7:00 A.M.', null=True, validators=[home.models.Professors.validate_start_time]),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='Room_Type',
            field=models.CharField(choices=[('Laboratory', 'Laboratory'), ('Lecture', 'Lecture')], default='Lecture', max_length=200),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='lab_or_lec',
            field=models.CharField(choices=[('Laboratory', 'Laboratory'), ('Lecture', 'Lecture')], default='Lecture', max_length=200),
        ),
        migrations.CreateModel(
            name='CollegeOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.colleges')),
                ('department_model', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_parental_key', to='home.departments')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
