# Generated by Django 3.1.8 on 2021-05-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_departmentorderable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollegeOrderable',
        ),
    ]
