# Generated by Django 3.1.8 on 2021-05-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_collegeorderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='Choose_College',
            field=models.CharField(choices=[('COS', 'COS'), ('CAFA', 'CAFA'), ('CIE', 'CIE')], max_length=100, null=True),
        ),
    ]
