# Generated by Django 3.1.8 on 2021-05-10 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_departments_choose_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='Choose_College',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colleges'),
        ),
    ]
