# Generated by Django 3.1.8 on 2021-05-11 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210510_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='professors',
            name='choose_college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colleges'),
        ),
        migrations.AddField(
            model_name='professors',
            name='choose_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.departments'),
        ),
    ]
