# Generated by Django 3.1.8 on 2021-05-12 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210512_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professors',
            name='choose_department',
            field=models.ForeignKey(limit_choices_to={'Choose_College_id': 10}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.departments'),
        ),
    ]
