# Generated by Django 3.1.8 on 2021-05-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_filteredcollege'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilteredCollege',
        ),
    ]
