# Generated by Django 3.1.8 on 2021-05-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_delete_filteredcollege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='Room_Name',
            field=models.CharField(help_text='Ex. Room101', max_length=20, null=True),
        ),
    ]
