# Generated by Django 3.1.8 on 2021-05-18 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210518_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='sem',
        ),
    ]
