# Generated by Django 3.1.8 on 2021-05-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_subjects_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='sem',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default='First', max_length=200),
        ),
    ]
