# Generated by Django 3.1.8 on 2021-05-18 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_subjects_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='sem',
        ),
    ]
