# Generated by Django 3.1.8 on 2021-05-18 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_subjects_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professors',
            name='choose_college',
        ),
    ]
