# Generated by Django 3.1.8 on 2021-05-18 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_subjects_sem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminsAccount',
        ),
        migrations.DeleteModel(
            name='ProfessorsAccount',
        ),
        migrations.DeleteModel(
            name='ProfessorsSchedule',
        ),
        migrations.DeleteModel(
            name='RoomsSchedule',
        ),
        migrations.DeleteModel(
            name='SectionsSchedule',
        ),
        migrations.DeleteModel(
            name='StudentsAccount',
        ),
    ]
