# Generated by Django 3.1.8 on 2021-05-18 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_professors_choose_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecurriculum',
            old_name='ending_year',
            new_name='curriculum_year',
        ),
        migrations.RemoveField(
            model_name='coursecurriculum',
            name='college',
        ),
        migrations.RemoveField(
            model_name='coursecurriculum',
            name='starting_year',
        ),
        migrations.AlterField(
            model_name='departments',
            name='Choose_College',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.colleges'),
        ),
    ]
