# Generated by Django 3.1.8 on 2021-05-18 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210518_1446'),
        ('home', '0029_auto_20210518_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='professororderable',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.professors'),
        ),
    ]
