# Generated by Django 3.1.8 on 2021-05-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210518_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sections',
            options={'ordering': ['course_name'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.RemoveField(
            model_name='sections',
            name='college',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='section_name',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='year_level',
        ),
        migrations.AddField(
            model_name='sections',
            name='course_name',
            field=models.CharField(help_text='Ex. BSCS', max_length=30, null=True),
        ),
    ]
