# Generated by Django 3.1.8 on 2021-05-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20210518_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sections',
            options={'ordering': ['section_name'], 'verbose_name': 'Sections', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AddField(
            model_name='sections',
            name='first_year',
            field=models.CharField(default=0, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sections',
            name='fourth_year',
            field=models.CharField(default=0, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sections',
            name='ns_first_year',
            field=models.CharField(default=0, max_length=256, null=True, verbose_name='First Year'),
        ),
        migrations.AddField(
            model_name='sections',
            name='ns_fourth_year',
            field=models.CharField(default=0, max_length=256, null=True, verbose_name='Fourth Year'),
        ),
        migrations.AddField(
            model_name='sections',
            name='ns_second_year',
            field=models.CharField(default=0, max_length=256, null=True, verbose_name='Second Year'),
        ),
        migrations.AddField(
            model_name='sections',
            name='ns_third_year',
            field=models.CharField(default=0, max_length=256, null=True, verbose_name='Third Year'),
        ),
        migrations.AddField(
            model_name='sections',
            name='second_year',
            field=models.CharField(default=0, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sections',
            name='section_name',
            field=models.CharField(help_text='Ex. BSCS-3A-NS', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sections',
            name='third_year',
            field=models.CharField(default=0, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='sections',
            name='year_level',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default='First', max_length=200),
        ),
    ]
