# Generated by Django 3.1.8 on 2021-05-18 13:36

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20210518_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectsorderable',
            name='course_curriculum_model',
        ),
        migrations.AddField(
            model_name='subjectsorderable',
            name='course_curriculum_model1',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_year_first_sem', to='home.coursecurriculum'),
        ),
        migrations.AddField(
            model_name='subjectsorderable',
            name='course_curriculum_model2',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_year_second_sem', to='home.coursecurriculum'),
        ),
        migrations.AddField(
            model_name='subjectsorderable',
            name='course_curriculum_model3',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_year_first_sem', to='home.coursecurriculum'),
        ),
        migrations.AddField(
            model_name='subjectsorderable',
            name='course_curriculum_model4',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_year_second_sem', to='home.coursecurriculum'),
        ),
        migrations.AddField(
            model_name='subjectsorderable',
            name='course_curriculum_model5',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_year_first_sem', to='home.coursecurriculum'),
        ),
        migrations.AddField(
            model_name='subjectsorderable',
            name='course_curriculum_model6',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_year_second_sem', to='home.coursecurriculum'),
        ),
        migrations.AddField(
            model_name='subjectsorderable',
            name='course_curriculum_model7',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_year_first_sem', to='home.coursecurriculum'),
        ),
        migrations.AddField(
            model_name='subjectsorderable',
            name='course_curriculum_model8',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_year_second_sem', to='home.coursecurriculum'),
        ),
    ]
