# Generated by Django 3.1.8 on 2021-05-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20210518_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sections',
            options={'ordering': ['section_name'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.RemoveField(
            model_name='sections',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='first_year',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='fourth_year',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='ns_first_year',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='ns_fourth_year',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='ns_second_year',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='ns_third_year',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='second_year',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='third_year',
        ),
    ]
