# Generated by Django 3.1.8 on 2021-05-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20210526_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='first_year',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='fourth_year',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='ns_first_year',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='ns_fourth_year',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='ns_second_year',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='ns_third_year',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='second_year',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='third_year',
        ),
    ]
