# Generated by Django 3.1.8 on 2021-05-28 06:13

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20210526_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='Ex. BSCS', max_length=30, null=True)),
                ('sem', models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default='First', max_length=200)),
                ('first_year', models.CharField(default=0, max_length=256, null=True)),
                ('second_year', models.CharField(default=0, max_length=256, null=True)),
                ('third_year', models.CharField(default=0, max_length=256, null=True)),
                ('fourth_year', models.CharField(default=0, max_length=256, null=True)),
                ('ns_first_year', models.CharField(default=0, max_length=256, null=True, verbose_name='First Year')),
                ('ns_second_year', models.CharField(default=0, max_length=256, null=True, verbose_name='Second Year')),
                ('ns_third_year', models.CharField(default=0, max_length=256, null=True, verbose_name='Third Year')),
                ('ns_fourth_year', models.CharField(default=0, max_length=256, null=True, verbose_name='Fourth Year')),
                ('course_curriculum', models.ForeignKey(help_text='Ex. Computer Science', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.coursecurriculum')),
                ('department', models.ForeignKey(help_text='Ex. Computer Studies', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.departments')),
            ],
            options={
                'verbose_name': 'Bulk Section',
                'verbose_name_plural': 'Bulk Section',
                'ordering': ['course_name'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
    ]
