# Generated by Django 3.1.8 on 2021-05-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_bulksections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulksections',
            options={'ordering': ['course_curriculum__course_name'], 'verbose_name': 'Bulk Section', 'verbose_name_plural': 'Bulk Section'},
        ),
        migrations.RemoveField(
            model_name='bulksections',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='bulksections',
            name='department',
        ),
    ]
