# Generated by Django 3.1.8 on 2021-06-07 04:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'ordering': ['college_name'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='CourseCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='Ex. CS33', max_length=300, null=True)),
                ('curriculum_year', models.PositiveIntegerField(help_text='Use the following format: <YYYY> ex: 2012', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)])),
            ],
            options={
                'verbose_name': 'Course Curriculum',
                'verbose_name_plural': 'Course Curriculum',
                'ordering': ['course_name'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_Name', models.CharField(help_text='Department of Mathematics', max_length=100, null=True)),
                ('Choose_College', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.colleges')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['Department_Name'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProfessorsSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Name', models.CharField(help_text='Ex. Room101', max_length=20, null=True)),
                ('Room_Type', models.CharField(choices=[('Laboratory', 'Laboratory'), ('Lecture', 'Lecture')], default='Lecture', max_length=200)),
            ],
            options={
                'verbose_name': 'Rooms',
                'verbose_name_plural': 'Rooms',
                'ordering': ['Room_Name'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='RoomsSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SectionsSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(help_text='Ex. CS33', max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('units', models.IntegerField(default=1)),
                ('lab_or_lec', models.CharField(choices=[('Laboratory', 'Laboratory'), ('Lecture', 'Lecture')], default='Lecture', max_length=200)),
                ('hours', models.FloatField(default=1)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['subject_code'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='SubjectsOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('course_curriculum_model1', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_year_first_sem', to='base.coursecurriculum')),
                ('course_curriculum_model2', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_year_second_sem', to='base.coursecurriculum')),
                ('course_curriculum_model3', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_year_first_sem', to='base.coursecurriculum')),
                ('course_curriculum_model4', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_year_second_sem', to='base.coursecurriculum')),
                ('course_curriculum_model5', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_year_first_sem', to='base.coursecurriculum')),
                ('course_curriculum_model6', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_year_second_sem', to='base.coursecurriculum')),
                ('course_curriculum_model7', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_year_first_sem', to='base.coursecurriculum')),
                ('course_curriculum_model8', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_year_second_sem', to='base.coursecurriculum')),
                ('professor_model', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_parental_key', to='accounts.professors')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.subjects')),
                ('subject_model', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_parental_key', to='base.subjects')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(help_text='Ex. BSCS-3A-NS', max_length=30, null=True)),
                ('year_level', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default='First', max_length=200)),
                ('sem', models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default='First', max_length=200)),
                ('course_curriculum', models.ForeignKey(help_text='Ex. Computer Science', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.coursecurriculum')),
                ('department', models.ForeignKey(help_text='Ex. Computer Studies', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.departments')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['section_name'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='RoomOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.rooms')),
                ('room_model', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_parental_key', to='base.departments')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessorOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor_orderable', to='accounts.professors')),
                ('room_model', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_parental_key', to='base.departments')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('college_model', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='college_parental_key', to='base.colleges')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.departments')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='coursecurriculum',
            name='department',
            field=models.ForeignKey(help_text='Ex. Computer Studies', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.departments'),
        ),
        migrations.CreateModel(
            name='BulkSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default='First', max_length=200)),
                ('first_year', models.IntegerField(default=0, null=True)),
                ('second_year', models.IntegerField(default=0, null=True)),
                ('third_year', models.IntegerField(default=0, null=True)),
                ('fourth_year', models.IntegerField(default=0, null=True)),
                ('ns_first_year', models.IntegerField(default=0, null=True, verbose_name='First Year')),
                ('ns_second_year', models.IntegerField(default=0, null=True, verbose_name='Second Year')),
                ('ns_third_year', models.IntegerField(default=0, null=True, verbose_name='Third Year')),
                ('ns_fourth_year', models.IntegerField(default=0, null=True, verbose_name='Fourth Year')),
                ('course_curriculum', models.ForeignKey(help_text='Ex. Computer Science', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.coursecurriculum')),
            ],
            options={
                'verbose_name': 'Bulk Section',
                'verbose_name_plural': 'Bulk Section',
                'ordering': ['course_curriculum__course_name'],
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
    ]
