# Generated by Django 3.1.8 on 2021-06-07 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210607_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectsorderable',
            old_name='course_curriculum_model1',
            new_name='first_year_first_sem',
        ),
        migrations.RenameField(
            model_name='subjectsorderable',
            old_name='course_curriculum_model2',
            new_name='first_year_second_sem',
        ),
        migrations.RenameField(
            model_name='subjectsorderable',
            old_name='course_curriculum_model7',
            new_name='fourth_year_first_sem',
        ),
        migrations.RenameField(
            model_name='subjectsorderable',
            old_name='course_curriculum_model8',
            new_name='fourth_year_second_sem',
        ),
        migrations.RenameField(
            model_name='subjectsorderable',
            old_name='course_curriculum_model3',
            new_name='second_year_first_sem',
        ),
        migrations.RenameField(
            model_name='subjectsorderable',
            old_name='course_curriculum_model4',
            new_name='second_year_second_sem',
        ),
        migrations.RenameField(
            model_name='subjectsorderable',
            old_name='course_curriculum_model5',
            new_name='third_year_first_sem',
        ),
        migrations.RenameField(
            model_name='subjectsorderable',
            old_name='course_curriculum_model6',
            new_name='third_year_second_sem',
        ),
        migrations.RemoveField(
            model_name='bulksections',
            name='ns_first_year',
        ),
        migrations.RemoveField(
            model_name='bulksections',
            name='ns_fourth_year',
        ),
        migrations.RemoveField(
            model_name='bulksections',
            name='ns_second_year',
        ),
        migrations.RemoveField(
            model_name='bulksections',
            name='ns_third_year',
        ),
        migrations.RemoveField(
            model_name='coursecurriculum',
            name='department',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='department',
        ),
        migrations.RemoveField(
            model_name='subjectsorderable',
            name='subject_model',
        ),
        migrations.AddField(
            model_name='coursecurriculum',
            name='choose_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.departments', verbose_name='department'),
        ),
        migrations.AddField(
            model_name='coursecurriculum',
            name='course_abbreviation',
            field=models.CharField(help_text='Ex. BSCS', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='choose_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.departments', verbose_name='department'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='choose_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.departments', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='coursecurriculum',
            name='course_name',
            field=models.CharField(help_text='Ex. Bachelor of Science in Computer Science', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='departments',
            name='Choose_College',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.colleges', verbose_name='College'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='lab_or_lec',
            field=models.CharField(choices=[('Laboratory', 'Laboratory'), ('Lecture', 'Lecture')], default='Lecture', max_length=200, verbose_name='Type'),
        ),
    ]
