# Generated by Django 3.1.8 on 2021-06-15 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210607_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomorderable',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.rooms'),
        ),
    ]
