# Generated by Django 3.1.8 on 2021-06-15 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210615_1905'),
        ('accounts', '0002_auto_20210607_1215'),
        ('schedule', '0003_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.professors'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='base.rooms'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='school_year',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='base.sections'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='starting_time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='base.subjects'),
        ),
    ]
