# Generated by Django 3.1.8 on 2021-06-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20210617_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='school_year',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
