# Generated by Django 3.1.8 on 2021-06-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210616_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_scheduler',
            field=models.BooleanField(default=False),
        ),
    ]
